### ISSUE TITLE
incorrect mix-manifest.json entry for files with a dot in name

### ISSUE THREAD

**Issue by tpetry** [ctf0/laravel-mix-versionhash#11]
* You have a file `iframeResizer.contentWindow.js` with dots in its filename
* You wan to process it with laravel-mix `.js('iframeResizer.contentWindow.js', 'public/js')`

Laravel-mix-versionhash will add the versionhash to the filename in the key of mix-manifest.json:
```
{
    "/js/iframeResizer.contentWindow.5321b25a.js": "/js/iframeResizer.contentWindow.5321b25a.js"
}
```

**Comment by ctf0** [comment]
can u try to change the `delimiter` option to something else other than `.` and try again ?

**Comment by tpetry** [comment]
It seems to fix the issue but that is not really the intended solution.

**Comment by ctf0** [comment]
atm changing the `contenthash` to `hash` will create new file for css on each run

**Comment by ctf0** [comment]
yes i understand, i will try to fix it when i have time

**Comment by omarkhatibco** [comment]
Hello @ctf0 

can you publish the fix please ?

**Comment by ctf0** [comment]
@omarkhatibco sadly i hadn't found enough time to work on this or others yet, any help is appreciated though
