### ISSUE TITLE
mix-manifest.json incorrect file name key

### ISSUE THREAD

**Issue by tpetry** [ctf0/laravel-mix-versionhash#14]
Keys within `mix-manifest.json` file for `laravel-mix-versionhash@1.0.5` are missing some extension name characters. So `somefile.css` will be `somefile.s` for the `mix-manifest.json` key. It's doing this for every file:
```json
{
  "/js/app.s": "/js/app.cad03a0e.js",
  "/js/iframeResizer-contentWindow.s": "/js/iframeResizer-contentWindow.969c49fe.js",
  "/css/app.s": "/css/app.75623058.css",
  "/css/tinymce-editor.s": "/css/tinymce-editor.75623058.css"
}
```

**Comment by ctf0** [comment]
this is mostly related to the new version of laravel-mix v4, which version r u using ?

**Comment by bolechen** [comment]
+1

**Comment by tpetry** [comment]
Like issue #11 the error is again within the logic for transforming the mix-manifest.json. Replacing the filename key is the culprit. It looks like the regular expression filename change is to error-prone, i think a more sophisticated logic is required

JSON before modification:
```
{
   "/js/app.cad03a0e.js":"/js/app.cad03a0e.js",
   "/js/iframeResizer-contentWindow.969c49fe.js":"/js/iframeResizer-contentWindow.969c49fe.js",
   "/css/app.75623058.css":"/css/app.75623058.css",
   "/css/tinymce-editor.75623058.css":"/css/tinymce-editor.75623058.css"
}
```

JSON after modification:
```json
{
   "/js/app.s":"/js/app.cad03a0e.js",
   "/js/iframeResizer-contentWindow.s":"/js/iframeResizer-contentWindow.969c49fe.js",
   "/css/app.s":"/css/app.75623058.css",
   "/css/tinymce-editor.s":"/css/tinymce-editor.75623058.css"
}
```

**Comment by tpetry** [comment]
I debugged the code which is transforming the filenames and came to the conclusion that regular expression is too unspecific. It's matching anything before the file extension which is the reason of #11.

The following regular expressions are solving this issue and #11 by being more specific:
```js
const removeHashFromKeyRegex = new RegExp(delimiter + '\.([a-f0-9]+)\.(.+)$', 'g')
const removeHashFromKeyRegexWithMap = new RegExp(delimiter + '\.([a-f0-9]+)\.(.+)\.map$', 'g')
```

These regular expressions are searching for a hex character sequence (the structure of a hash) surrounded by dots in the filename.

**Comment by tpetry** [comment]
It‘s just replacing the old regeyes with the new ones. Can make a pull request on thursday or friday.

**Comment by ctf0** [comment]
i will do it then, are u sure it doesnt effect anything else ?

**Comment by tpetry** [comment]
Pretty sure. It‘s just a better regexp. But i currently see that you support configurable delimeters, will have to change the regex to support this.

**Comment by ctf0** [comment]
i will wait for ur PR then
