### ISSUE TITLE
Support versioning Extra Files

### ISSUE THREAD

**Issue by lidoma** [ctf0/laravel-mix-versionhash#16]
Hi
The `mix.versionHash()` does not version extra files which passed as an array of paths.
```php
mix.version(['public/js/random.js']);
```

https://laravel-mix.com/docs/4.0/versioning#versioning-extra-files

**Comment by ctf0** [comment]
btw isnt the same as using `.copy` ?

**Comment by Erutan409** [comment]
@ctf0 This would tie into #10 and how this plugin would solve for that problem.

**Comment by ctf0** [comment]
@Erutan409 does https://github.com/ctf0/laravel-mix-versionhash/pull/24 tackle this one as well ?

**Comment by Erutan409** [comment]
@ctf0 Not quite, just yet. So long as the latest changes are good with you, the new method can be abstracted further to be used for this, specifically.

So, keep this one open and I'll get this one knocked out fairly quick.
