### ISSUE TITLE
Proper this.options context issue when plugin is registered, but not used.

### ISSUE THREAD

**Issue by Erutan409** [ctf0/laravel-mix-versionhash#27]
@ctf0 Seems like there may have been an issue introduced with various refactoring since my last PR.  I'm going to push a fix in an hour or two and submit the PR.

**Comment by ctf0** [comment]
sure np, thanx

**Comment by Erutan409** [comment]
@ctf0 I need more time to work on it.  The webpack build needs to complete before any subsequent modifications should occur (combine).  So, I'm going to abstract it out a little further so that it's not complicated to support.

**Comment by ctf0** [comment]
can u tell me more of what is the issue exactly ?

**Comment by Erutan409** [comment]
If you register the plugin, but don't invoke the register method, you'll see the error.  And it's because of the way that the method for hashing files outside of the webpack context are handled/triggered.  It's an invocation order issue.  So, what I'm trying to do now is abstract out the proxying a little more, so it's more like a promise, while detecting if the plugin was actually used.

When Laravel Mix loads the plugin with `.extend()`, it's invoking the plugin's constructor, which binds the funcitonality for hashing the combined assets.  But, that doesn't mean the plugin is actually being used.  So, the options config (which is created when actually invoking the plugin), isn't being set on the `this` context of the instance.  And causing errors with the new combine hashing functionality.

**Comment by queued** [comment]
I think I ran into this very issue. However, I could not detect which plugin is being registered but not used as of this writing. The only current fix for my problem has been completely disabling ```mix.versionHash()``` from my *webpack.config.js*

**Comment by ctf0** [comment]
@Erutan409 any news ?
