### ISSUE TITLE
Regression: mix.*.js is being created again

### ISSUE THREAD

**Issue by wolfgang42** [ctf0/laravel-mix-versionhash#32]
I just tested with the latest version on npm (1.1.1) and #9 (extra mix.js file being generated) is happening again. `git bisect` says the problem was introduced by #23.

**Comment by ctf0** [comment]
@Erutan409

**Comment by Erutan409** [comment]
@ctf0 I'll take a look around 12 PM EST, today.

**Comment by Erutan409** [comment]
@wolfgang42 I'm not able to reproduce this with my setup.  Can you provide something that would?

**Comment by wolfgang42** [comment]
@Erutan409 Repro gist here: https://gist.github.com/wolfgang42/e605124edef6b0081a3e98a78aa02313

**Comment by Erutan409** [comment]
@wolfgang42 FYI - I didn't forget to look into this.  I have some outstanding items that need to be completed before the end of the year.  I'll try to get into this before then, though.
