### ISSUE TITLE
Don't add hash on images, fonts, etc...

### ISSUE THREAD

**Issue by jcolfej** [ctf0/laravel-mix-versionhash#33]
We currently use mix.version() but we need hash to be a part of filename for cache and have a 404 on other hash value.

This plugin solve the problem for JS and CSS file but don't do the job for images or fonts...

Can you add these feature ? <3 <3 <3

**Comment by ctf0** [comment]
this is the part responsible for hashing imgs,fonts,etc..
https://github.com/ctf0/laravel-mix-versionhash/blob/193e26c83a1e33a0dd68624950b54fd60d366ee2/src/index.js#L99-L160

we can add a new option to allow/ignore hashing them, can u make a PR with that ?

**Comment by JosuelRocha** [comment]
@ctf0 what our colleague meant is that although here at github the code is hash implementation in files inside css but in the npm package it is coming without this part of the code in version 1.1.1, it needs to update the npm repository with last code.

https://prnt.sc/qqbqpl

**Comment by ctf0** [comment]
ah yes, will publish it now
