### ISSUE TITLE
Doesn't delete old versions

### ISSUE THREAD

**Issue by cashmeer** [ctf0/laravel-mix-versionhash#34]
Hello, I think you missed the easiest feature here, This package should behave exactly the same as Mix version as it replaces old versions with new ones , doesn't just create a new version upon old files.

<img width="206" alt="Capture d’écran 2020-04-06 à 22 44 23" src="https://user-images.githubusercontent.com/24992264/78608103-2ddaf180-7858-11ea-8b21-7e59af1eb456.png">

**Comment by ctf0** [comment]
actually with version the file is overwritten because the file name hash is saved into manifest.json, but with this plugin the name is written to disk.

so the behavior is expected :+1:

**Comment by cashmeer** [comment]
Yes I understand, would be cool if it removed prev versions before saving
the new one. Optional feature at least 👌

**Comment by ctf0** [comment]
u can use https://github.com/johnagan/clean-webpack-plugin , already in the rdme 👍
