### ISSUE TITLE
Version 1.1.5 breaks build with TypeError: mix.listen is not a function

### ISSUE THREAD

**Issue by mfos239** [ctf0/laravel-mix-versionhash#38]
Version 1.1.2 works fine for me but 1.1.5 throws this error on build

TypeError: mix.listen is not a function
    at VersionHash.registerHashAssets (node_modules/laravel-mix-versionhash/src/index.js:194:13)

**Comment by ctf0** [comment]
v1.1.3 added https://github.com/ctf0/laravel-mix-versionhash/commit/ecb992c4552ed3fa52017586925011c046f51197
v1.1.5 added https://github.com/ctf0/laravel-mix-versionhash/commit/751d0a23f21a267f040045171576d7590d16f4e3

so am not sure what exactly whould through this, any ideas ?

**Comment by mfos239** [comment]
1.1.3 builds without error. I found the breaking changes between 1.1.3 and 1.1.5 were introduced in this commit:

https://github.com/ctf0/laravel-mix-versionhash/tree/569e128713c32cdbb6e156aee360255b5a33c68b

Mix was changed to lowercase mix in the following instances:

`mix.listen('build', () => {`
https://github.com/ctf0/laravel-mix-versionhash/commit/569e128713c32cdbb6e156aee360255b5a33c68b#diff-1fdf421c05c1140f6d71444ea2b27638R190

`const file = File.find(`${Config.publicPath}/${mix.manifest.name}`)`
https://github.com/ctf0/laravel-mix-versionhash/commit/569e128713c32cdbb6e156aee360255b5a33c68b#diff-1fdf421c05c1140f6d71444ea2b27638R196

`proxyMethod.before(mix, 'addTask', (task) => {`
https://github.com/ctf0/laravel-mix-versionhash/commit/569e128713c32cdbb6e156aee360255b5a33c68b#diff-1fdf421c05c1140f6d71444ea2b27638R222

If I change it back to Mix, the build succeeds.

**Comment by ctf0** [comment]
ah yes,i made that change because of https://github.com/ctf0/laravel-mix-versionhash/blob/569e128713c32cdbb6e156aee360255b5a33c68b/src/index.js#L1 which is lower case

**Comment by mfos239** [comment]
Yes but they are not the same

**Comment by ctf0** [comment]
okay, np, can u plz send a PR ?

**Comment by ctf0** [comment]
@mfos239 can u test the latest commit ?

**Comment by mfos239** [comment]
I can test it tomorrow thank you

**Comment by craigpotter** [comment]
@ctf0 - I tested this commit and it works now. I was getting the same issue as @mfos239 before.

**Comment by ctf0** [comment]
sorry for that, I will publish a new version today.

thanx again for reporting.

**Comment by mfos239** [comment]
New version works perfect. Thanks for the quick fix @ctf0
