### ISSUE TITLE
Hashing for "scripts"?

### ISSUE THREAD

**Issue by flatcapco** [ctf0/laravel-mix-versionhash#41]
Hey thanks for the package, I've got it setup in a Wordpress project and it's working a charm on my sass files.

However I'm combining js files using mix.scripts and I'd expected this to create a hash too.

Am I missing something?

I don't really want to run any of the fancy javascript stuff just combining and minifying multiple files into 1 with a unique hash

Thank you!

**Comment by ctf0** [comment]
i dont think we support that atm, but plz check https://github.com/ctf0/laravel-mix-versionhash/issues/10 and reply back if it tackles ur request.
