### ISSUE TITLE
Support for laravel-mix v6

### ISSUE THREAD

**Issue by oza75** [ctf0/laravel-mix-versionhash#42]
I try to use this plugin with laravel-mix@^6.0.0-beta.15 but I'm getting `compiler.plugin is not a function error`. I guess v6 is not supported yet. isn't it ?

**Comment by ctf0** [comment]
i havent tested with the new version but probably not yet.

**Comment by olivM** [comment]
this fork works well with laravel-mix@6 : https://github.com/Aslam97/laravel-mix-versionhash

**Comment by olivM** [comment]
pull request is here : https://github.com/ctf0/laravel-mix-versionhash/pull/43

**Comment by ctf0** [comment]
@olivM thankx alot for that, @oza75 can u test on ur side as well ?

**Comment by olivM** [comment]
> @olivM thankx alot for that

kudos to @Aslam97
