### ISSUE TITLE
No longer generating hashed filenames with laravel-mix 2.1.14

### ISSUE THREAD

**Issue by mikerogerz** [ctf0/laravel-mix-versionhash#7]

**Comment by ctf0** [comment]
i have the same version of mix and its working without issues, can u give more info of ur setup ?

**Comment by mikerogerz** [comment]
It seems to be specific to my laravel-mix config (vuejs ssr) and the new
version of laravel-mix, where mix.version() isn't working correctly either.

You can close this issue, thanks. I'll reach out if I find anything
specific to your plugin.
