### ISSUE TITLE
Breaks BrowserSync in some cases

### ISSUE THREAD

**Issue by octoxan** [ctf0/laravel-mix-versionhash#8]
See https://github.com/JeffreyWay/laravel-mix/issues/1686

BrowserSync doesn't work in Magento 1 unless you explicitly set what files to watch.

The following code works.
```js
mix.options({
    processCssUrls: false,
    })
    .setPublicPath(path.resolve('./'))
    .sass('skin/frontend/example/default/scss/styles.scss', 'skin/frontend/example/default/dist/')
    .version()
    .browserSync({
        proxy: 'example.test',
        files: [
            'skin/frontend/example/default/dist/*.css',
        ]
    });
```

But switching it to `versionHash()` makes it not inject stylesheet changes. I even tried setting the delimiter to a hyphen thinking maybe the extra period was breaking `*.css`

**Comment by oliverpool** [comment]
this could also work:
```js
if (mix.inProduction()) {
    require("laravel-mix-versionhash");
    mix.versionHash();
} else {
    mix.browserSync({
        proxy: "localhost:8000"
    });
}

```
