### ISSUE TITLE
/public/mix.*.js created when no mix.js() given

### ISSUE THREAD

**Issue by wolfgang42** [ctf0/laravel-mix-versionhash#9]
I'm using Laravel Mix for SCSS compilation, but not JS. If I don't have any `mix.js()` calls in `webpack.mix.json`, I get a `public/mix.08780b.js` (though the hash seems to vary) with a blank webpackBootstrap boilerplate.

**Comment by ctf0** [comment]
i think i have found the issue

when u dont use a js file `laravel-mix` will use auto add a js file call `'xxx/node_modules/laravel-mix/src/builder/mock-entry.js',` under the `mix` entry and therefore create an unnecessary file

atm i dont have enough knowledge to fix it, so anyone can help plz do

**Comment by jellycode** [comment]
I think we need to check the webpackConfig.entry to see if 'js' is called. If not, no need to change the output.filename?

**Comment by ctf0** [comment]
actually if no js file is used, `laravel-mix` will add a default empty entry, however am not sure why changing the `output.filename` have side effects.

**Comment by Erutan409** [comment]
@ctf0 Has there been any headway on this?

**Comment by ctf0** [comment]
sadly no :cry:

**Comment by Erutan409** [comment]
I figured it out.  Here's what's happening:

Laravel Mix does use a [mock entry plugin](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/webpackPlugins/MockEntryPlugin.js) that will [test for the existence of an unnecessary `mix.js` file](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/webpackPlugins/MockEntryPlugin.js#L16).  That is, Laravel Mix, by default, doesn't actually change the file of the versioned asset, as it just [suffixes it with a query string](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/Manifest.js#L56) at the end.

When I changed the code, here, with the following:

```js
class MockEntryPlugin {
    /**
     * Handle the deletion of the temporary mix.js
     * output file that was generated by webpack.
     *
     * This file is created when the user hasn't
     * requested any JavaScript compilation, but
     * webpack still requires an entry.
     *
     * @param {Object} compiler
     */
    apply(compiler) {
        compiler.plugin('done', stats => {
            let temporaryOutputFile = stats
                .toJson()
                .assets.find(asset => /^mix(?:\W.*?)?\.js$/i.test(asset.name));

            if (temporaryOutputFile) {
                delete stats.compilation.assets[temporaryOutputFile.name];

                File.find(
                    path.resolve(Config.publicPath, temporaryOutputFile.name)
                ).delete();
            }
        });
    }
}

module.exports = MockEntryPlugin;
```

The file is removed with your plugin.  Notice the change in the `.assets.find( ... )` logic.

You may need to add subsequent logic to look for this file as the code above is doing.

**Comment by ctf0** [comment]
@Erutan409 can u make a PR for this ?

**Comment by Erutan409** [comment]
@ctf0 I'd love to.  I'd just need to figure out the best/elegant way to accomplish it without breaking @JeffreyWay's intended fluent API.

**Comment by ctf0** [comment]
i was thinking of making it through the lib, so maybe check if the `mix.js` size is zero then delete it but of course it will add extra unnecessary time to the build :(

**Comment by Erutan409** [comment]
@ctf0 I'll see what I can come up with.  I have an idea that may work without going outside the intended extending.

**Comment by ctf0** [comment]
@wolfgang42 can u check if the latest commit fix ur issue ?

**Comment by wolfgang42** [comment]
Yes, I've just confirmed this problem is gone as of ca3a67c8076a6f70db0642cd42b5eed3d093e57a.
